### ISSUE TITLE
evaluatePolicy calls have localizedReason parameter hard coded as English string

### ISSUE THREAD

**Issue by benjmartellopi** [EOSIO/eosio-swift-vault#57]
private func signWithBioCheck calls evaluatePolicy(.deviceOwnerAuthenticationWithBiometrics, **localizedReason: "Sign Transaction"**, reply: { (isValid, error) ...

The **_localizedReason_** parameter is used in a system alert and with it being a hard coded English string here the app incorporating this SDK cannot change what is displayed.

This needs to be made something the implementing app can set appropriately so it can actually be localized for the country / language needed and to be adjusted as needed for application purposes.

**Comment by opi-smccoole** [comment]
Fixed in version 0.3.0
