### ISSUE TITLE
"Error was encountered in key management"

### ISSUE THREAD

**Issue by VadimSos** [EOSIO/eosio-swift-vault#65]
Following the tutorial in https://github.com/EOSIO/eosio-swift-vault for EosioSwiftVault I wrote the following function:

import EosioSwiftVault

func getKeyPair()
let vault = EosioVault(accessGroup: Bundle.main.bundleIdentifier!)
    do{
        let key = try vault.newVaultKey(secureEnclave: true)
    } catch { print(error)
    }

It prints out the following:
Error was encountered in key management.

**Comment by jke661s** [comment]
I got this error as well. Have no clue how to fix it.

**Comment by opi-smccoole** [comment]
Are you trying to run it on a device or the simulator?  Simulator does not have the secure enclave.

**Comment by jke661s** [comment]
Thank you. It works after I configured an App Group and run it on my device.
